# Generated by Django 5.1.2 on 2024-11-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_alter_tarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epica',
            options={'permissions': [('puede_eliminar_epica', 'Puede eliminar epica')]},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'permissions': [('puede_completar_tarea', 'Puede completar tarea'), ('puede_eliminar_tarea', 'Puede eliminar tarea')]},
        ),
    ]
