# Generated by Django 5.1.2 on 2024-11-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_alter_epica_options_alter_tarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epica',
            options={'permissions': [('puede_modificar_epica', 'Puede modificar epica')]},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'permissions': [('puede_completar_tarea', 'Puede completar tarea'), ('puede_modificar_tarea', 'Puede modificar tarea')]},
        ),
    ]
